export const USER_LOGIN_ATTEMPT = "USER::LOG_USER_IN_ATTEMPT";
export const USER_LOGIN_SUCCESSFUL = "USER::LOG_USER_IN_FULFILLED";
export const USER_LOGIN_FAILED = "USER::LOG_USER_IN_FAILED";
export const USER_LOGOUT = "USER::LOG_USER_OUT";
